---
title: "Simulating, creating spatial proxies, and sampling"
author: Jakub Nowosad
date: "`r Sys.Date()`"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(simsam)
library(terra)
```

```{r}
rast_grid = terra::rast(ncols = 200, nrows = 200, 
                        xmin = 0, xmax = 200, ymin = 0, ymax = 200)
```

## Simulate

```{r}
sim_rast = sim_field(rast_grid, 100, scenario = "autocor", n_covariates = 6)
plot(sim_rast)
```

```{r}
sim_rast1 = sim_field(rast_grid, 10, scenario = "autocor", n_covariates = 4)
sim_rast2 = sim_field(rast_grid, 100, scenario = "autocor", n_covariates = 4)
sim_rast3 = sim_field(rast_grid, 10, scenario = "random", n_covariates = 4)
sim_rast4 = sim_field(rast_grid, 100, scenario = "random", n_covariates = 4)
panel(c(sim_rast1[[1]], sim_rast2[[1]], sim_rast3[[1]], sim_rast4[[1]]), 
      nc = 2)
```

## Create spatial proxies

```{r}
proxy_coords = make_proxy(sim_rast, "coordinates")
plot(proxy_coords)
proxy_edf = make_proxy(sim_rast, "edf")
plot(proxy_edf)
proxy_ogc = make_proxy(sim_rast, "ogc", 5)
plot(proxy_ogc)
```

## Sample

```{r}
set.seed(2024-11-20)
sample_j1 = sam_field(rast_grid, 100, "jittered", 5)
plot(sample_j1)
sample_j2 = sam_field(rast_grid, 100, "jittered", 20)
plot(sample_j2)
sample_r = sam_field(rast_grid, 100, "random")
plot(sample_r)
sample_c1 = sam_field(rast_grid, 100, "clustered", nclusters = 5, value = 10)
plot(sample_c1)
sample_c2 = sam_field(rast_grid, 100, "clustered", nclusters = 5, value = 20)
plot(sample_c2)
```



